FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
WORKDIR /app
COPY requirements-bad.txt .
RUN pip install --no-cache-dir -r requirements-bad.txt
COPY . .
CMD ["python", "src/nvidia_locked_benchmark.py"]
